CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'mahasiswa')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    nim VARCHAR(30) NOT NULL UNIQUE,
    nama VARCHAR(150) NOT NULL,
    prodi VARCHAR(120) NOT NULL,
    angkatan SMALLINT NOT NULL CHECK (angkatan BETWEEN 1900 AND 2200),
    ipk_terakhir NUMERIC(3,2) NOT NULL CHECK (ipk_terakhir BETWEEN 0 AND 4),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS students_prodi_idx ON students (prodi);
CREATE INDEX IF NOT EXISTS students_angkatan_idx ON students (angkatan);

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_mk VARCHAR(30) NOT NULL UNIQUE,
    nama_mk VARCHAR(180) NOT NULL,
    sks SMALLINT NOT NULL CHECK (sks BETWEEN 1 AND 24),
    semester SMALLINT NOT NULL CHECK (semester BETWEEN 1 AND 14),
    kuota INTEGER NOT NULL CHECK (kuota >= 0)
);

CREATE INDEX IF NOT EXISTS courses_semester_idx ON courses (semester);

CREATE TABLE IF NOT EXISTS enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    tahun_akademik VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT enrollments_student_course_year_key
        UNIQUE (student_id, course_id, tahun_akademik)
);

CREATE INDEX IF NOT EXISTS enrollments_student_id_idx ON enrollments (student_id);
CREATE INDEX IF NOT EXISTS enrollments_course_id_idx ON enrollments (course_id);
